### ISSUE TITLE
Make a CLI using this library

### ISSUE THREAD

**Issue by gu1ll0me** [ccr-tools/python-ccr#10]

**Comment by rshipp** [comment]
This should take place in a new branch of ccr-tools. We should eventually update both the 'ccr' and 'ccr-tools' bash scripts to use this lib.

**Comment by gu1ll0me** [comment]
Same thing for the GUI app?

**Comment by rshipp** [comment]
Well the GUI should actually just be a part of Shaman2 eventually. This can only happen once akabei is more done though, so if you want to make a simple gui in the meantime it's up to you where you want to put it.

**Comment by rshipp** [comment]
Future work in https://github.com/ccr-tools/python-ccr-cli.
