### ISSUE TITLE
Create a requirements.txt

### ISSUE THREAD

**Issue by rshipp** [ccr-tools/python-ccr#12]

**Comment by gu1ll0me** [comment]
Can you give me some hints on what you would have in this file and how it should be used?

**Comment by rshipp** [comment]
http://www.pip-installer.org/en/latest/logic.html#requirements-file-format
I don't know what dependencies python-ccr has anymore. If it's only requests, the requirements.txt would just be:

```
requests>=2.0.1
```

This doesn't do anything for Chakra's packaging, but will be important if we put python-ccr on PyPi.
