### ISSUE TITLE
Unused branches

### ISSUE THREAD

**Issue by gu1ll0me** [ccr-tools/python-ccr#18]
Can we delete oop, unittest and except branches?

**Comment by rshipp** [comment]
Yes to `oop` and `except`. It looks like @Inkane made some changes in `unittest` that were never merged in - are those obsolete now?

**Comment by rshipp** [comment]
I deleted `oop` and `except`. `unittest` has some changes that look useful, so I'm leaving it until I decide what should be cherry-picked into `development`.

**Comment by rshipp** [comment]
Done. I'm leaving `unittest` for archival reasons and closing this issue.
