### ISSUE TITLE
Add most functions from ccr-tools, and others

### ISSUE THREAD

**Issue by rshipp** [ccr-tools/python-ccr#2]
Specifically:
  {un}vote()
  check()
  submit()

Also add things suggested for ccr-tools, including:
  comment()
  delete()
  {un}flag()
  setcategory()
  {un}notify()
  disown()/adopt()

**Comment by rshipp** [comment]
Vote/unvote, check, flag/unflag, notify/unnotify, disown/adopt are done, along with some others. 
Comment will not be added, submit will be added once I find a way to upload files with urllib2, and delete will be added as soon as submit is done.

**Comment by rshipp** [comment]
Everything but submit, delete, and getlatest is done.

**Comment by Inkane** [comment]
finished submit, delete and getlatest
