### ISSUE TITLE
local sqlite database

### ISSUE THREAD

**Issue by rshipp** [ccr-tools/python-ccr#3]
Create and maintain a local sqlite database with all necessary package information. Add functions to update this database, and change current functions to look up information from the database. 

If possible, create some efficient method to only modify/insert changed/new entries in the online database to the local one, so that rebuilding the database from scratch each time is unneccessary. Possibly look at the python-aur module for ideas.

**Comment by gu1ll0me** [comment]
I try to download the complete list of ccr packages with the search method (rpc.php?type=search...). I would like to have the same result as clicking on the Go button on the CCR page without entering any search (all packages result). Is that possible with rpc.php?

If not, should i use "http://chakra-project.org/ccr/packages.php?O=0&K=&do_Search=+Go+" ?

**Comment by rshipp** [comment]
I don't think rpc.php allows that, and the search link is paginated, so probably not very helpful either (at least without a ton of work and nasty html scraping). In the future (with the Django app), we should replace rpc.php entirely with a REST API, at which time this will be easy. Alternatively, if we want it done faster and there's an easy fix, we could just edit rpc.php.

Anyone else know if I'm wrong and there is currently some way to get all packages?

**Comment by gu1ll0me** [comment]
As you wish for modifying rpc.php but i think it will be better to fit python-ccr module functionnalities with the new django app. Is there a repo where i could follow the developement of the django app?

**Comment by rshipp** [comment]
Gitorious: https://gitorious.org/chakra/chakraweb/
Trello card: https://trello.com/c/bnqS7E9w/7-ccr-application

**Comment by rshipp** [comment]
I think the only use for this would be offline package searching, which isn't very important. I'm closing the issue. Feel free to reopen in the future if someone disagrees.
