### ISSUE TITLE
Store username and password

### ISSUE THREAD

**Issue by gu1ll0me** [ccr-tools/python-ccr#7]
Use a config file to store username and password and KWallet as option.

**Comment by rshipp** [comment]
Could this be optional? It would be nice if the lib still functioned without KDE installed.

**Comment by gu1ll0me** [comment]
OK. I will store the information in a config file first and give the option for KWallet

**Comment by rshipp** [comment]
Just had a thought- wouldn't this make more sense in a cli/gui script of some sort, instead of in the library? Libraries don't usually have configuration files.

**Comment by gu1ll0me** [comment]
It makes sense. But maybe it is good too to have a standardized way to store this information. If there is a CLI (ccr) and a GUI (Shaman2), the method of CCRSession could be used for both apps. It souldn't be necessary to write two codes.

You propose to maintain a local sqlite db, username and password could be stored in this one.

**Comment by rshipp** [comment]
Good idea.

**Comment by Inkane** [comment]
With my software engineering hat on: It would be nice if the library would use a "credential interface", basically, an object which has methods to store and receive credentials. The library would only depend on this interface, and could maybe ship with a dummy implementation, which does nothing. Then we could have additional "addons", which implement e.g. storing the credentials in a file, in a db or in KWallet. And yes, I'm aware of the fact that this might be a bit overengineered. But it also would make unit testing easier, IMHO.

**Comment by rshipp** [comment]
I know how this would work in Java, with interfaces. What is the Python way of accomplishing this?

**Comment by gu1ll0me** [comment]
I read something about abstract classes, it could be that way.

**Comment by Inkane** [comment]
One could e.g. create just a normal class, which does nothing, and let the addons derive from it. Of course we can also use abc.ABCMeta, but that might be a bit TOO overengineered.

**Comment by rshipp** [comment]
OK, so just pretend we have such a thing as abstract classes. :)

**Comment by gu1ll0me** [comment]
Just to make sure i got it, it is something like that? A CCRAuth class (the interface), classes CCRAuthFile, CCRAuthSQLite and CCRAuthKWallet will be derived from CCRAuth? Shaman2 and ccr-cli will use CCRAuthFile/SQLite/KWallet to manage the user account?

file ccrauth.py
#!/usr/bin/python3
"""A class to manage CCR authentication"""

class CCRAuth:

```
def login(self, username, password, remember_me):
""" some code here """

def logout(self):
""" some code here """

def forgot_password(self, email):
""" some code here """

def change_password(self, password):
""" some code here """

def change_email(self, email):
""" some code here """

def store_account_info(self):
""" reimplemented in file, sqlite, kwallet classes """
```

file ccrauthsqlite.py
#!/usr/bin/python3
import ccrauth

class CCRAuthSQLite(CCRAuth):
    """ some code here """

**Comment by Inkane** [comment]
@michaudg : Yes, basically like that.
