### ISSUE TITLE
Listing the most recent changes to the CCR

### ISSUE THREAD

**Issue by gu1ll0me** [ccr-tools/python-ccr#8]

**Comment by gu1ll0me** [comment]
@Inkane, you told me some weeks ago to add this functionnality to the module but i wonder what "recent changes" would you like to see exactly. Does the getlatest() function do this already?

```
def getlatest(num=10):
    """get the info for the latest num CCR packages, returns as a list"""
    return _get_ccr_json(LATEST, str(num))
```

**Comment by Inkane** [comment]
That one will indeed return the latest changes; it will however not only list new packages, but also updated ones which existed before. A new method which returns only the latest new packages might also be helfpull. There might however be no API available to do it.

**Comment by rshipp** [comment]
No method exists for this in the current CCR webapp. I'm closing the issue, feel free to reopen if this changes.
